"""Steps bin/sync runs after third-party skills are installed or updated.

    python3 post_install.py BACKUP_DIR [--apply]

1. Codex ignores `disable-model-invocation: true` in SKILL.md frontmatter and
   reads `policy.allow_implicit_invocation` from agents/openai.yaml instead.
   Give every installed skill that sets the former, and ships no openai.yaml,
   one that says the same thing, so Codex matches Claude Code and Cursor.
   Updates replace skill folders, so this runs on every sync.
2. Write ~/.config/principles.md: one line per principle-* skill, from pstack
   or from this repo, saying when it applies and where its SKILL.md is.
3. Point each agent's global instructions at that index, inside a marked
   block this script owns.

Prints one plan line per change, in bin/sync's format. With --apply, copies
each instruction file into BACKUP_DIR before changing it.
"""
from pathlib import Path
import re
import shutil
import sys

HOME = Path.home()
SKILLS = HOME / ".agents" / "skills"
INDEX = HOME / ".config" / "principles.md"
INSTRUCTIONS = [
    HOME / ".claude" / "CLAUDE.md",
    HOME / ".codex" / "AGENTS.md",
    HOME / ".config" / "opencode" / "AGENTS.md",
]
CODEX_META = """\
# Written by fleet bin/sync: SKILL.md sets disable-model-invocation, which
# Codex ignores. This keeps Codex from invoking the skill on its own.
policy:
  allow_implicit_invocation: false
"""
BLOCK_START = "<!-- fleet:principles (managed by fleet bin/sync) -->"
BLOCK_END = "<!-- /fleet:principles -->"
BLOCK = f"""{BLOCK_START}
Before nontrivial code work (design, implementation, debugging, review), read
`~/.config/principles.md` and apply the principles that fit. Read a
principle's SKILL.md in full before applying it. When running `code-review`,
add the principles that match the diff to the Standards sources, ranked below
the repo's documented standards.
{BLOCK_END}
"""


def short(path):
    path = str(path)
    return "~/" + path[len(str(HOME)) + 1:] if path.startswith(str(HOME) + "/") else path


def say(verb, text):
    print(f"  {verb:<10} {text}")


def frontmatter(skill_dir):
    try:
        text = (skill_dir / "SKILL.md").read_text()
    except (FileNotFoundError, NotADirectoryError):
        return {}
    match = re.match(r"---\n(.*?)\n---", text, re.S)
    fields = {}
    for line in (match.group(1) if match else "").splitlines():
        key, sep, value = line.partition(":")
        if sep and not line.startswith((" ", "\t")):
            fields[key.strip()] = value.strip().strip('"').strip("'")
    return fields


def installed():
    """Third-party skills: real folders in ~/.agents/skills (own skills are symlinks)."""
    if not SKILLS.is_dir():
        return []
    return sorted(p for p in SKILLS.iterdir() if p.is_dir() and not p.is_symlink())


def backup(path, backup_dir):
    if path.exists():
        saved = backup_dir / path.relative_to(HOME)
        saved.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, saved)


def codex_meta(apply):
    for skill in installed():
        meta = skill / "agents" / "openai.yaml"
        if frontmatter(skill).get("disable-model-invocation") == "true" and not meta.exists():
            say("codex-meta", f"{skill.name}: not implicitly invoked")
            if apply:
                meta.parent.mkdir(exist_ok=True)
                meta.write_text(CODEX_META)


def index_text():
    lines = [
        "<!-- Generated by fleet bin/sync from the installed principle-* skills. -->",
        "",
        "# Engineering principles",
        "",
        "Each line says when a principle applies and where its SKILL.md is. Read the",
        "file in full before applying the principle.",
        "",
    ]
    # Own principles are symlinks from this repo, so list every folder.
    for skill in sorted(SKILLS.glob("principle-*")):
        if skill.is_dir():
            description = frontmatter(skill).get("description", "")
            lines.append(f"- **{skill.name[len('principle-'):]}**: {description} "
                         f"`~/.agents/skills/{skill.name}/SKILL.md`")
    return "\n".join(lines) + "\n"


def write_index(apply, backup_dir):
    text = index_text()
    if text.count("\n- **") == 0 and not INDEX.exists():
        return  # no principles installed yet
    if INDEX.exists() and INDEX.read_text() == text:
        return
    say("write", short(INDEX))
    if apply:
        backup(INDEX, backup_dir)
        INDEX.parent.mkdir(parents=True, exist_ok=True)
        INDEX.write_text(text)


def pointers(apply, backup_dir):
    for path in INSTRUCTIONS:
        if not path.parent.is_dir():
            continue
        text = path.read_text() if path.exists() else ""
        pattern = re.compile(re.escape(BLOCK_START) + r".*?" + re.escape(BLOCK_END) + r"\n?", re.S)
        if pattern.search(text):
            updated = pattern.sub(lambda _: BLOCK, text)
        else:
            updated = text + ("\n" if text and not text.endswith("\n") else "") + ("\n" if text else "") + BLOCK
        if updated == text:
            continue
        say("pointer", f"{short(path)}: read ~/.config/principles.md")
        if apply:
            backup(path, backup_dir)
            path.write_text(updated)


def main(argv):
    backup_dir, apply = Path(argv[0]), "--apply" in argv
    codex_meta(apply)
    write_index(apply, backup_dir)
    pointers(apply, backup_dir)


if __name__ == "__main__":
    main(sys.argv[1:])
